# Site settings
title: Research School of Earth Sciences - Data Science Theme
subtitle: The Australian National University
longtitle: Research School of Earth Sciences - The Australian National University
email: malcolm.samridge@anu.edu.au
description: Webpage of the RSES Data Science Theme
baseurl: "/rses-datascience.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: Research School of Earth Sciences, The Australian National University
city: Canberra
state: ACT
zip_code: 2601
country: Australia
#phone: (716) 555-5555

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown

sass:
  style: compressed
